[package]
name = "create-token-program"
version = "0.1.0"
edition = "2021"

[dependencies]
borsh.workspace = true
borsh-derive.workspace = true
solana-program.workspace = true
spl-token = { version = "8.0.0", features = [ "no-entrypoint" ] }
spl-associated-token-account = { version = "7.0.0", features = [ "no-entrypoint" ] }
mpl-token-metadata = { version = "5.1.1", features = [ "no-entrypoint" ] }

[lib]
crate-type = ["cdylib", "lib"]

[features]
anchor-debug = []
custom-heap = []
custom-panic = []

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(target_os, values("solana"))'] }
