[package]
name = "steel-hello-solana"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]

[dev-dependencies]
base64 = "0.21"
rand = "0.8.5"
solana-sdk = "^1.18"
tokio = { version = "1.35", features = ["full"] }

[dependencies]
bytemuck = "1.14"
num_enum = "0.7"
solana-program = "^1.18"
steel = "2.0"
thiserror = "1.0"
# ~
